Makefile
=> Update make clean

deploy.sh
Fix a bug in the CI script.
/cc @ewang12
=> Fix a bug in the CI script

main.tex
Introduce `using` into the `provide` construct.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-provide-using.pdf) is a link to the PDF generated from this PR.
=> Introduce `using`

main.tex
T-Application was getting long enough to hit the figure frame, so I updated it to use shortstack.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-use-shortstack.pdf) is a link to the PDF generated from this PR.
@stepchowfun
=> Use shortstack for T-Application

main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-provide.pdf) is a link to the PDF generated from this PR.
@stepchowfun
=> Fix T-Provide to correctly propagate effects

main.tex
Formalize the structural rules (it was bothering me that we had weakening but not permutation). Also, add an explanation for syntax that is used in the typing rules but not defined in the grammar.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-structural-rules.pdf) is a link to the PDF generated from this PR.
=> Formalize the structural rules

README.md
Update README.md to reflect the new repository name. Also testing that the Travis CI integration works after the rename!
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-rename-repo.pdf) is a link to the PDF generated from this PR.
=> Update README.md to reflect the new repository name

main.tex
Make keywords bold. Right now the only keywords we have are in the `effect` syntax.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-bold-keywords.pdf) is a link to the PDF generated from this PR.
=> Make keywords bold

main.tex
Formalize the idea of effect masking and remove the structural rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-xusing.pdf) is a link to the PDF generated from this PR.
=> Formalize the idea of effect masking and remove the structural rules

main.tex
Add a variable freshness condition to `T-Effect`, just like the one in `T-Abstraction`. (Also, reorder the premises to make them look slightly nicer.)
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-operation-freshness.pdf) is a link to the PDF generated from this PR
=> Add a variable freshness condition to T-Effect

.gitignore, Makefile, deploy.sh, formalization/examples.v, formalization/syntax.v, formalization/typingRules.v
Split the formalization into multiple files.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-organization.pdf) is a link to the PDF generated from this PR.
=> Split the formalization into multiple files

main.tex
Remove unit.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-unit.pdf) is a link to the PDF generated from this PR.
=> Remove unit

main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-add-effect-preserving-app.pdf) is a link to the PDF generated from this PR.
=> Restore effect-preserving application

main.tex
Add kinds.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-syntax-kinds.pdf) is a link to the PDF generated from this PR.
=> Add syntax for kinds

main.tex
Fix T-Effect.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-t-effect.pdf) is a link to the PDF generated from this PR.
=> Fix T-Effect

main.tex
Revert stepchowfun/delimited-effects#55.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-revert-55-t-effect.pdf) is a link to the PDF generated from this PR.
=> Revert "Fix T-Effect"

main.tex
Add kind equivalence rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kind-equivalence.pdf) is a link to the PDF generated from this PR.
=> Add kind equivalence rules

main.tex
Update T-Effect with higher kinds.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-new-t-effect.pdf) is a link to the PDF generated from this PR.
=> Use new kinds in T-Effect

main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-provide.pdf) is a link to the PDF generated from this PR.
=> Fix T-Provide

main.tex
Add scheme equivalence rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-scheme-equivalence.pdf) is a link to the PDF generated from this PR.
=> Add scheme equivalence rules

main.tex
Stack the premises for `T-EffectPreservingApplication`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-stack-eappxp.pdf) is a link to the PDF generated from this PR.
=> Stack the premises for T-EffectPreservingApplication

main.tex
Adjust some cosmetic stuff and fix a small bug. The bug fix is to change `\anno{\sscheme_1}{\ktype}` to `\tjudgment{\ccontext}{\sscheme_1}{\ktype}` in `T-Effect`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-style.pdf) is a link to the PDF generated from this PR.
=> Adjust some cosmetic stuff and fix a small bug

Makefile, formalization/judgments.v, main.tex
Add skeletons of the judgments. I filled in the first rule of every judgement. I also fixed a few typos in the paper.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-judgments.pdf) is a link to the PDF generated from this PR.
=> Add skeletons of the judgments

formalization/judgments.v
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-wellformed-judgements.pdf) is a link to the PDF generated from this PR.
=> Add well formedness judgements

formalization/judgments.v, main.tex
Remove subkinding.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-subkinding.pdf) is a link to the PDF generated from this PR.
=> Remove subkinding

formalization/judgments.v, formalization/syntax.v, main.tex
Formalize the subtyping rules. I also fixed a few bugs along the way.
=> Formalize the subtyping rules

formalization/subsumption.v
Reorder the definitions and proofs regarding subsumption. I think this order is more intuitive.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subsumption-ordering.pdf) is a link to the PDF generated from this PR.
=> Reorder the definitions and proofs regarding subsumption

formalization/helpers.v, formalization/judgments.v, formalization/syntax.v, main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-rename-tptwithx.pdf) is a link to the PDF generated from this PR.
=> Rename type with effects to use r instead of x

formalization/helpers.v
Fix indentation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-indentation.pdf) is a link to the PDF generated from this PR.
=> Fix indentation

formalization/helpers.v, formalization/judgments.v, formalization/subtyping.v, formalization/syntax.v, main.tex
Temporarily simplify the system (both in LaTeX and Coq) to make formalization easier.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-simplify.pdf) is a link to the PDF generated from this PR.
=> Temporarily simplify the system to make formalization easier

Makefile, paper/main.tex
Write some sample content for the introduction. This is obviously not the final copy (I hope!), just something to get us started and give us a sense of what it will look like.
A couple technical changes:
- Introduce some boilerplate for formatting code blocks. I think it might be nice to have some human-friendly syntax for examples.
- The linters really hate the code examples, and there's no way to disable them just for those listings. I think the linters have been more troublesome than useful in general, so this PR removes them entirely.
Both of those are up for discussion! Nothing is permanent.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-writing.pdf) is a link to the PDF generated from this PR.
=> Write some content

paper/main.tex
Move effects from the type level to the term level
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effects-as-terms.pdf) is a link to the PDF generated from this PR.
=> Effects as terms

scripts/deploy.sh
Simplify the deploy script slightly.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-deploy-script.pdf) is a link to the PDF generated from this PR.
=> Simplify the deploy script slightly

paper/main.tex
Do some minor copyediting.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-small-tweak.pdf) is a link to the PDF generated from this PR.
=> Do some minor copyediting

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-new-kinding-rules.pdf) is a link to the PDF generated from this PR.
=> Add kinding rules for the simplified syntax

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-kinding-rules.pdf) is a link to the PDF generated from this PR.
=> Fix kinding rules

paper/main.tex
Fix K-SingletonRow.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-map-lookup.pdf) is a link to the PDF generated from this PR.
=> Fix K-SingletonRow

paper/main.tex
Simplify the subtyping rules and fix a few small bugs.
=> Simplify the subtyping rules and fix a few small bugs

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kind-symbols.pdf) is a link to the PDF generated from this PR.
=> Update symbols for kinds

paper/main.tex
Remove unused macros and do some renaming.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-simplify-macros.pdf) is a link to the PDF generated from this PR.
=> Remove unused macros

paper/main.tex
Alphabetize the package list.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-alphabetize-package-list.pdf) is a link to the PDF generated from this PR.
=> Alphabetize the package list

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kind-symbol.pdf) is a link to the PDF generated from this PR.
=> Use circle for kind of a proper type

paper/main.tex
Do some minor copyediting on the statement of Theorem 1.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-row-membership.pdf) is a link to the PDF generated from this PR.
=> Do some minor copyediting on the statement of Theorem 1

paper/main.tex
Update the syntax for provide.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-provide-syntax.pdf) is a link to the PDF generated from this PR.
=> Update the syntax for provide

paper/main.tex
Add T-Provide.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-t-provide.pdf) is a link to the PDF generated from this PR.
=> Add T-Provide

paper/main.tex
Clean up the macros.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-macros.pdf) is a link to the PDF generated from this PR.
=> Clean up the macros

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subtyping-context.pdf) is a link to the PDF generated from this PR.
=> Remove context from subtyping relation

paper/main.tex
Fix _Theorem 1_.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-theorem-1.pdf) is a link to the PDF generated from this PR.
=> Fix Theorem 1

paper/main.tex
Fix Theorem 1 (again).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-theorem-1.pdf) is a link to the PDF generated from this PR.
=> Fix Theorem 1 (again)

paper/main.tex
Rename some rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-proper-type-with-effects.pdf) is a link to the PDF generated from this PR.
=> Rename some rules

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-op-type-well-formedness.pdf) is a link to the PDF generated from this PR.
=> Reintroduce type well-formedness

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-type-well-formed.pdf) is a link to the PDF generated from this PR.
=> Check the kinds of types in the effect map

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-add-wf-context.pdf) is a link to the PDF generated from this PR.
=> Add a context to the effect well-formedness judgment

paper/main.tex
Fix a typo.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-typo.pdf) is a link to the PDF generated from this PR.
=> Fix a typo

paper/main.tex
Introduce coeffects.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coeffects.pdf) is a link to the PDF generated from this PR.
=> Introduce coeffects

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formed-judgments.pdf) is a link to the PDF generated from this PR.
=> Use different judgments for effects and coeffects

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formed-abbrevs.pdf) is a link to the PDF generated from this PR.
=> Fix names of well-formed judgments

paper/main.tex
Introduce a metatheory section.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-metatheory.pdf) is a link to the PDF generated from this PR.
=> Introduce a metatheory section

paper/main.tex
Remove application by name.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-only-strict.pdf) is a link to the PDF generated from this PR.
=> Remove application by name

formalization/syntax.v, paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-update-syntax.pdf) is a link to the PDF generated from this PR.
=> Update syntax in coq

paper/main.tex
Add a stipulation to Theorem 1.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-theorem-1-stipulation.pdf) is a link to the PDF generated from this PR.
=> Add a stipulation to Theorem 1

paper/main.tex
Fix some subscripts.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subscripts.pdf) is a link to the PDF generated from this PR.
=> Fix some subscripts

paper/main.tex
Fix `T-TypeApplication` and `T-RowApplication` (to make them work like `T-Application`).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-type-application.pdf) is a link to the PDF generated from this PR.
=> Fix T-TypeApplication and T-RowApplication

paper/main.tex
Fix the well-formedness conditions. There were a few problems with them.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formedness.pdf) is a link to the PDF generated from this PR.
=> Fix the well-formedness conditions

paper/main.tex
Fix the well-formedness rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formedness.pdf) is a link to the PDF generated from this PR.
=> Fix the well-formedness rules

paper/main.tex
Remove coeffects.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-coeffects.pdf) is a link to the PDF generated from this PR.
=> Remove coeffects

paper/main.tex
Fix a few minor things:
- Indentation
- I renamed `\proper` to `\type`
- I fixed a small bug in `T-Abstraction`
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-minor-fixes.pdf) is a link to the PDF generated from this PR.
=> Fix a few minor things

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-effect-row-equivalence.pdf) is a link to the PDF generated from this PR.
=> Add axioms for row equivalence

implementation/implementation.cabal
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-change-email.pdf) is a link to the PDF generated from this PR.
=> Update email in cabal file

implementation/app/Main.hs, implementation/src/Lib.hs
Define a type for effect rows and add a skeleton for an equivalence relation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-row-equiv.pdf) is a link to the PDF generated from this PR.
=> Define a type for effect rows and add a skeleton for an equivalence relation

Makefile, implementation/app/Main.hs, implementation/implementation.cabal, implementation/src/Lib.hs, implementation/test/Spec.hs
Set up QuickCheck and add a test case.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-quickcheck.pdf) is a link to the PDF generated from this PR.
=> Set up QuickCheck

implementation/src/Lib.hs
Do what https://github.com/stepchowfun/delimited-effects/pull/201 did, but for the Arbitrary Row instance.
=> Simplify the Arbitrary instance for Row

implementation/src/Lib.hs, implementation/test/Spec.hs
Fix some style according to some style guide.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-style.pdf) is a link to the PDF generated from this PR.
=> Fix some style

implementation/implementation.cabal, implementation/stack.yaml, implementation/test/Spec.hs
Make the test case more robust.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-stream.pdf) is a link to the PDF generated from this PR.
=> Make the test case more robust

implementation/src/Lib.hs, implementation/test/Spec.hs
I'm trying to make the code nicer to read and more consistent, but I'm not actually sure if these are improvements.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-style.pdf) is a link to the PDF generated from this PR.
=> Make the style more consistent

implementation/src/Lib.hs, implementation/test/Spec.hs
Clarify the base case for `elimPairs`. Also I fixed a couple style issues and removed a few unnecessary deriving directives.
=> Clarify the base case for elimPairs

implementation/src/Lib.hs
Replace BA... with BR... for "Boolean ring" (it was "Boolean algebra" before).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-br.pdf) is a link to the PDF generated from this PR.
=> Replace BA... with BR... for 'Boolean ring'

paper/main.tex
Temporarily switch to the simply-typed lambda calculus to make things simpler.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-simply-typed.pdf) is a link to the PDF generated from this PR.
=> Temporarily switch to the simply-typed lambda calculus

implementation/src/Lib.hs
Rename BRSingleton to BRAtom.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-atom.pdf) is a link to the PDF generated from this PR.
=> Rename BRSingleton to BRAtom

implementation/implementation.cabal, implementation/src/Lib.hs
Simplify effect row normalization (and fix a bug in the `BRAnd` case in which the result may not have been completely normalized).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-normalize.pdf) is a link to the PDF generated from this PR.
=> Simplify effect row normalization

formalization/syntax.v, implementation/src/Lib.hs, implementation/test/Spec.hs, paper/main.tex
Make the paper, formalization, and implementation all agree. This means (temporarily) removing polymorphism from the formalization and implementation to match the paper.
From now on, should we always keep them in sync?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-paper-formalization-implementation-correspondence.pdf) is a link to the PDF generated from this PR.
=> Make the paper, formalization, and implementation all agree

implementation/test/Spec.hs
Speed up the subrow specs by skipping test cases in which all the effects occur (like we used to do). Once we re-introduce variables (non-exclusive atoms), this will be required anyway (for the first spec).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-spec.pdf) is a link to the PDF generated from this PR.
=> Speed up the subrow specs by skipping test cases in which all the effects occur

Makefile, implementation/src/Subrow.hs, implementation/src/Syntax.hs, implementation/test/LibSpec.hs, implementation/test/SubrowSpec.hs, implementation/test/SyntaxSpec.hs
Add some syntax-related helper functions and choose a metavariable naming scheme.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-syntax.pdf) is a link to the PDF generated from this PR.
=> Add some syntax-related helper functions and choose a metavariable naming scheme

implementation/src/Syntax.hs, implementation/test/SubrowSpec.hs, implementation/test/SyntaxSpec.hs
Run every spec a million times.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-frequency.pdf) is a link to the PDF generated from this PR.
=> Run every spec a million times

implementation/src/Lib.hs, implementation/src/Subtype.hs, implementation/src/Syntax.hs
Sort imports and exports. Also make the style more consistent.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-imports-exports.pdf) is a link to the PDF generated from this PR.
=> Sort imports and exports

implementation/implementation.cabal, implementation/src/Inference.hs, implementation/src/Lib.hs, implementation/src/Subtype.hs, implementation/src/Syntax.hs, implementation/test/InferenceSpec.hs, implementation/test/LibSpec.hs
Implement type and effect row inference.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-inference.pdf) is a link to the PDF generated from this PR.
=> Implement type and effect row inference

implementation/src/Inference.hs, implementation/src/Syntax.hs
@esdrw discovered this bug and is working on a PR for the corresponding fix in the LaTeX.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-provide-implementation.pdf) is a link to the PDF generated from this PR.
=> Fix the implementation of T-Provide

implementation/src/Inference.hs, implementation/src/Syntax.hs, implementation/test/InferenceSpec.hs, implementation/test/SyntaxSpec.hs, paper/main.tex
Fix some minor syntactical issues in T-Provide.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-t-provide.pdf) is a link to the PDF generated from this PR.
=> Fix some minor syntactical issues in T-Provide

paper/main.tex
x is already being used for term variables.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-update-boolean-variable.pdf) is a link to the PDF generated from this PR.
=> Use z for variable in the boolean ring language

paper/main.tex
Combine the two well-formedness figures into one.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formedness.pdf) is a link to the PDF generated from this PR.
=> Combine the two well-formedness figures into one

formalization/syntax.v, implementation/src/Inference.hs, implementation/src/Syntax.hs, paper/main.tex
Rename 'provide' to 'handle'.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-instance.pdf) is a link to the PDF generated from this PR.
=> Rename 'provide' to 'handle'

paper/main.tex
Update a bunch of macros.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-macros.pdf) is a link to the PDF generated from this PR.
=> Update a bunch of macros

implementation/test/SubrowSpec.hs
Simplify the subrow spec.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-spec.pdf) is a link to the PDF generated from this PR.
=> Simplify the subrow spec

scripts/Dockerfile
Explicitly specify the Coq version (I am paranoid).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-version.pdf) is a link to the PDF generated from this PR.
=> Pin the Coq version

implementation/app/Main.hs, implementation/implementation.cabal, implementation/src/Inference.hs, implementation/src/Lexer.x, implementation/src/Parser.y, implementation/src/Syntax.hs, implementation/test/InferenceSpec.hs, implementation/test/LexerSpec.hs, implementation/test/LibSpec.hs, implementation/test/ParserSpec.hs
Add a basic lexer and parser, and replace unit with booleans. This lexer doesn't have full support for type annotations, since that would require deciding on a syntax for effect rows.
=> Add a lexer and parser

formalization/Syntax.v, implementation/examples/conditional, implementation/src/Inference.hs, implementation/src/Lexer.x, implementation/src/Parser.y, implementation/src/Syntax.hs, paper/main.tex
Add conditionals (`if`/`then`/`else`). Without this, our Booleans are pretty useless!
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-if.pdf) is a link to the PDF generated from this PR.
=> Add conditionals

paper/main.tex
Remove some unnecessary subscripts. @esdrw caught this.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subscripts.pdf) is a link to the PDF generated from this PR.
=> Remove some unnecessary subscripts

Makefile, implementation/app/Main.hs, implementation/src/Error.hs, implementation/src/Inference.hs, implementation/src/Subrow.hs, implementation/src/Syntax.hs, implementation/stack.yaml, implementation/test/ErrorSpec.hs, implementation/test/LexerSpec.hs, implementation/test/ParserSpec.hs, implementation/test/SyntaxSpec.hs, scripts/Dockerfile, scripts/travis-deploy.sh
Add automatic formatting for Haskell code with [brittany](https://github.com/lspitzner/brittany).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-brittany.pdf) is a link to the PDF generated from this PR.
=> Add automatic formatting for Haskell code

paper/main.tex
Remove hoisting until we finalize the effect system.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-delete-hoisting.pdf) is a link to the PDF generated from this PR.
=> Temporarily remove hoisting

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-subscripts.pdf) is a link to the PDF generated from this PR.
=> Fix typing rules after deleting hoisting

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-rules.pdf) is a link to the PDF generated from this PR.
=> Fix rules again

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-better-t-app.pdf) is a link to the PDF generated from this PR.
=> Allow more effects in a function argument

paper/main.tex
Remove some unnecessary parentheses.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-parens.pdf) is a link to the PDF generated from this PR.
=> Remove some unnecessary parentheses

paper/main.tex
Propose a new syntax for effect definitions. What do you think?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-where.pdf) is a link to the PDF generated from this PR.
=> Propose a new syntax for effect definitions

formalization/Syntax.v
Update the Coq to match the paper.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq.pdf) is a link to the PDF generated from this PR.
=> Update the Coq to match the paper

implementation/src/Inference.hs, implementation/src/Lib.hs, implementation/src/Syntax.hs, implementation/test/SubrowSpec.hs, implementation/test/SyntaxSpec.hs, paper/main.tex
Implement inference for monomorphic user-defined effects, and fix a typo in the paper.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-implement-user-effects-haskell.pdf) is a link to the PDF generated from this PR.
=> Implement inference for monomorphic effects

paper/main.tex
Formalize the target language.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-target.pdf) is a link to the PDF generated from this PR.
=> Formalize the target language

paper/main.tex
Add the syntax of the source language.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-source.pdf) is a link to the PDF generated from this PR.
=> Add the syntax of the source language

paper/main.tex
Reintroduce hoisting.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-hoisting.pdf) is a link to the PDF generated from this PR.
=> Reintroduce hoisting

paper/main.tex
Switch from superscripts to exclamation points.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-exclamation.pdf) is a link to the PDF generated from this PR.
=> Switch from superscripts to exclamation points

paper/main.tex
Add some spaces for consistency with related macros (no visual change).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-spaces.pdf) is a link to the PDF generated from this PR.
=> Add some spaces for symmetry with related macros

paper/main.tex
Be more consistent about coloring rows.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-row-color.pdf) is a link to the PDF generated from this PR.
=> Be more consistent about coloring rows

paper/main.tex
Choose more contrasting colors.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-colors.pdf) is a link to the PDF generated from this PR.
=> Choose more contrasting colors

paper/main.tex
Add some missing colors.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-colors.pdf) is a link to the PDF generated from this PR.
=> Add some missing colors

paper/main.tex
Add back the assumptions I deleted in the previous PR.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-assumptions.pdf) is a link to the PDF generated from this PR.
=> Add back the assumptions I deleted in the previous PR

paper/main.tex
Reorder the languages.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-core.pdf) is a link to the PDF generated from this PR.
=> Reorder the languages

implementation/src/Lib.hs, implementation/src/Subrow.hs, implementation/src/Syntax.hs, implementation/test/SubrowSpec.hs
Update the subrow function to match what will be in the paper.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow.pdf) is a link to the PDF generated from this PR.
=> Update the subrow function to match what will be in the paper

paper/main.tex
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-relation.pdf) is a link to the PDF generated from this PR.
=> Formalize the subrow relation

paper/main.tex
Rewrite a heading in sentence case to be consistent with the others.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-sentence-case.pdf) is a link to the PDF generated from this PR.
=> Rewrite a heading in sentence case

formalization/Subrow.v, formalization/Syntax.v, implementation/src/Syntax.hs
Formalize the subrow relation in Coq. I also fixed a few style/consistency issues and updated the Coq syntax to match the core language (not the source language) for now.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-coq.pdf) is a link to the PDF generated from this PR.
=> Formalize the subrow relation in Coq

paper/main.tex
Fix a bug in T-TApp.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-t-tapp-bug.pdf) is a link to the PDF generated from this PR.
=> Fix a bug in T-TApp

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, Makefile, scripts/post-artifact-link.rb, scripts/travis-deploy.sh
Add a robot to post a link to the build in the PR.
=> Add a robot to post a link to the build in the PR

.github/PULL_REQUEST_TEMPLATE.md
Remove the now-useless pull request template.
=> Remove the now-useless pull request template

paper/main.tex
Color the types correctly in the conclusion of T-TApp.
=> Fix colors in T-TApp

scripts/post-artifact-link.rb
=> Clarify the robot's message

Makefile
Be consistent about indentation.
=> Be consistent about indentation

formalization/Syntax.v, implementation/src/Inference.hs, implementation/src/Syntax.hs, paper/main.tex
Replace `Forall` with `ForAll`, since "for all" is two words.
=> Replace 'Forall' with 'ForAll'

Makefile, scripts/lint-tex.rb
Make some minor improvements to the LaTeX linter. The most important thing is the change to `MACRO_REGEX`, which fixes a bug.
=> Make some minor improvements to the LaTeX linter

scripts/lint-tex.rb
Add a whitelist of macros and their arities.
=> Add a whitelist of macros and their arities

paper/main.tex, scripts/lint-tex.rb
Add support for checking nested args in the LaTeX linter.
=> Add support for checking nested args in the LaTeX linter

scripts/Dockerfile
Upgrade Coq to 8.7.2. I am building the new image now.
=> Upgrade Coq to 8.7.2

Makefile, scripts/lint-imports.rb
Check for unused or unsorted imports in the formalization. I also reorganized the Makefile a little.
=> Check for unused or unsorted imports in the formalization

paper/macros.tex, paper/overview.tex
Switch to using math instead of code for the examples. The code just felt too out of place.
@esdrw
=> Switch to using math instead of code for the examples

paper/main.tex, paper/reflection.tex
Delete some unused stuff, especially stuff related to code formatting.
@esdrw
=> Delete some unused stuff

paper/entanglement.tex, paper/macros.tex, paper/reflection.tex
Add a translation semantics for the full calculus.
@esdrw
=> Add a translation semantics for the full calculus

formalization/Tactics.v
Add more flexible magic tactics.
=> Add more flexible magic tactics

.gitignore, Makefile, scripts/Dockerfile
=> Upgrade to Coq 8.8.0

.gitignore
Fix the `.gitignore` file.
@esdrw
=> Fix the .gitignore file

formalization/Tactics.v
Deduplicate some logic in the tactics.
@esdrw
=> Deduplicate some logic in the tactics

Makefile, README.md
Rename the repo from `delimited-effects` to `effect-classes`.
@esdrw
=> Rename the repo

implementation/README.md, implementation/app/Main.hs, implementation/src/Lexer.x, implementation/src/Parser.y
Improve the UX of the CLI. Now you are dropped into a REPL if no filename is provided. It took me forever to get Alex and Happy to do what I want (monadic parsing).
@esdrw
=> Improve the UX of the CLI

implementation/src/Inference.hs
This was an easy extension to implement. If a function's argument is completely unconstrained, it never requires a type annotation. Now we can fuly infer the type of "obvious" examples like this:
```haskell
> (\x -> x) (\y -> y)
(λ(x : ∀a . a -> a) . x) λ(a : *) (y : a) . y
: ∀a . a -> a
```
And even fancier examples like:
```haskell
> (\x y -> x) (\u v -> v) (\m n -> m)
(λ(x : ∀a . a -> a) (a : *) (y : ∀a . a -> ∀a . a -> a) . x) λ(a : *) (u : ∀a . a -> a) (a : *) (v : a) . v ∀a . a -> ∀a . a -> a λ(a : *) (m : ∀a . a -> a) (a : *) (n : a) . m
: ∀a . a -> ∀a . a -> a
```
@esdrw
=> Infer the type of fully polymorphic functions

implementation/src/Inference.hs, implementation/src/Syntax.hs
Organize the free variables functions into type classes.
@esdrw
=> Organize the free variables functions into type classes

implementation/src/Inference.hs, implementation/src/Syntax.hs
Make pretty printing a little more type safe.
=> Make pretty printing a little more type safe

implementation/src/Inference.hs
=> Add a comment

implementation/src/Lexer.x, implementation/src/Parser.y
Give slightly better parse error messages.
=> Give slightly better parse error messages

implementation/examples/test.g, implementation/src/Lexer.x, implementation/src/Parser.y
Remove the unnecessary let keyword.
=> Remove the unnecessary let keyword

implementation/app/Main.hs, implementation/examples/test.g, implementation/implementation.cabal, implementation/stack.yaml, implementation/test/LibSpec.hs
Clean up some infrastructure and make other miscellaneous small improvements.
@esdrw
=> Clean up some infrastructure

implementation/src/Inference.hs
Reimplement the type checker with some slightly nicer abstractions.
@esdrw
=> Reimplement the type checker

implementation/src/Inference.hs
Fix the `subsume` function.
@esdrw
=> Fix the subsume function

implementation/app/Main.hs, implementation/src/Parser.y
A picture is worth a thousand words:
And look at that type inference! 😄 
@esdrw
=> Make the repl slightly nicer with Unicode symbols

implementation/examples/test.g, implementation/implementation.cabal, implementation/src/Inference.hs, implementation/src/Lexer.x, implementation/src/Parser.y, implementation/src/Substitution.hs, implementation/src/Syntax.hs, implementation/test/LibSpec.hs, implementation/test/SubstitutionSpec.hs
Implement scoped type variables and delete "existential" type variables.
@esdrw
=> Implement scoped type variables

implementation/src/Inference.hs, implementation/src/Lexer.x, implementation/src/Syntax.hs
=> Use Greek letters for type variables

implementation/src/Parser.y
=> Clean up the parser

implementation/src/Lexer.x, implementation/src/Parser.y
=> Fix some error messages

implementation/src/Evaluation.hs, implementation/src/Inference.hs, implementation/src/Lexer.x, implementation/src/Parser.y, implementation/src/Substitution.hs, implementation/src/Syntax.hs
Implement list concatenation.
It would be nice to have automatic eta reduction to simplify the last example.
@esdrw
=> Implement list concatenation

implementation/src/Evaluation.hs, implementation/src/Inference.hs, implementation/src/Parser.y, implementation/src/Syntax.hs
Clean up and fix various things.
@esdrw
=> Clean up and fix various things

implementation/test/EvaluationSpec.hs, implementation/test/InferenceSpec.hs, implementation/test/LexerSpec.hs, implementation/test/LibSpec.hs, implementation/test/ParserSpec.hs, implementation/test/SubstitutionSpec.hs, implementation/test/SyntaxSpec.hs
Fix the name of a pending test.
=> Fix the name of a pending test

paper/calculus.tex, paper/overview.tex
Replace `monoid` with `monoidal`.
@esdrw
=> Replace 'monoid' with 'monoidal'

implementation/src/Inference.hs
Fix variable capture-related issues for type annotations. Free type variables in type annotations are treated as existentials (not scoped) in the sense described in the HMF paper. All type variables in annotations are replaced with auto-generated fresh variables as a pre-processing step to avoid any variable capture problems that might result from substitutions (e.g., in type applications).
@esdrw
=> Fix variable capture-related issues for type annotations

implementation/src/Inference.hs
Fix a bug in the type annotation logic.
@esdrw
=> Fix a bug in the type annotation logic

implementation/src/Evaluation.hs, implementation/src/Inference.hs, implementation/src/Syntax.hs
Refactor the pretty printer.
@esdrw
=> Refactor the pretty printer

implementation/examples/church.g, implementation/src/Inference.hs, implementation/src/Syntax.hs
Add types to the Church example and fix a couple small bugs related to pretty-printing.
@esdrw
=> Add types to the Church example

implementation/src/Syntax.hs
Rename some things for clarity.
@esdrw
=> Rename some things

implementation/app/Main.hs, implementation/examples/church.g, implementation/examples/lists.g, implementation/src/Parser.y, implementation/src/Syntax.hs
Fix a small bug and remove the special syntax for list types.
=> Fix a small bug and remove the special syntax for list types

implementation/src/Parser.y
Fix some indentation in the parser.
@esdrw
=> Fix some indentation in the parser

Makefile, scripts/Dockerfile
=> Add tagref

implementation/src/Inference.hs, implementation/src/Substitution.hs
Add a substitution accumulator in the context instead of passing around and composing substitutions explicitly.
@esdrw
=> Add a substitution accumulator in the context

paper/calculus.tex, paper/macros.tex, paper/overview.tex
Reformulate the semantics to be more concise and have less boilerplate. We went from 29 rules to 19!
@esdrw
=> Reformulate the semantics

implementation/implementation.cabal
Remove a duplicate dependency.
=> Remove a duplicate dependency

scripts/Dockerfile
=> Upgrade Coq to 8.8.2

Makefile
Add a `run-implementation` target to the `Makefile`.
=> Add a `run-implementation` target to the `Makefile`
