- Makefile
- deploy.sh
- main.tex
Add two LaTeX linters: lacheck and ChkTeX.
If we have this, we will need to require all changes to be made through PRs (unfortunately), but we don't need to require the PRs to be approved.
What do you think?
/cc @ewang12
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-lint.pdf) is a link to the PDF generated from this PR.
> Add LaTeX linters

- main.tex
Use `\evar` instead of `\pname`, since `provide` essentially introduces variables into scope that are used no differently from ordinary lambda-bound variables.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-pname.pdf) is a link to the PDF generated from this PR.
> Use \evar instead of \pname

- README.md
Add an icon to `README.md` showing the master build status. This is what it looks like:
[![Build Status](https://travis-ci.org/stepchowfun/long-distance-interaction.svg?branch=master)](https://travis-ci.org/stepchowfun/long-distance-interaction)
With this, we don't really need all changes to go through PRs. It will be easy enough to see if someone broke the build just by looking at the readme.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-build-status.pdf) is a link to the PDF generated from this PR.
> Add an icon to README.md showing the master build status

- deploy.sh
Move linting to the end of the CI build process. That way we can still see the PDF even when there are lint errors.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-lint-after-upload.pdf) is a link to the PDF generated from this PR.
> Move linting to the end of the CI build process

- main.tex
Introduce effect-preserving application and fix several things.
- Be consistent about spacing in macros
- Allow abstractions to have variables with effects
- Move the syntax for effect contexts to be next to that of type contexts
- Split applications into two forms: effect-realizing and effect-preserving
- Change the precedence from `E ! (a -> b)` to `(E ! a) -> b`
- Rename `T-Weaken` to `E-Weaken1`
- Add the `E-Weaken2` rule
- Add a new `T-Weaken` rule
- Use the Peyton-Jones et al. [1] style for the `T-Variable` rule (this style makes the `T-Weaken2` rule easier to formalize)
To be complete, we would need a permutation rule for type contexts and another permutation rule for effects. But I noticed that the Peyton-Jones et al. paper omits the type permutation rule, so we can live without …
> Introduce effect-preserving application and fix several things

- main.tex
Introduce user-defined effects (single operation for now) and fix some of the weakening rules.
Note: This PR also removes `provide`. What do you think?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-provide.pdf) is a link to the PDF generated from this PR.
> Introduce user-defined effects (single operation for now) and fix some of the weakening rules

- main.tex
Add a "Draft" watermark to the background. If anyone gets a copy of this PDF, they will know it's not the final version.
This seems like the simplest way to add the watermark. I just Googled it and picked the solution with the fewest dependencies.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-draft-watermark.pdf) is a link to the PDF generated from this PR.
> Add a "Draft" watermark to the background

- main.tex
Just use the effect name as the variable rather than putting it in a subscript.
Is this the correct thing to do?
Before:
After:
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-variable-name.pdf) is a link to the PDF generated from this PR.
> Just use the effect name as the variable rather than putting it in a subscript

- main.tex
Remove authors from the paper until we are ready to add them. The first submission needs to be anonymous anyway. I don't like having the authors on the paper right now because it might imply some kind of ordering.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-authors.pdf) is a link to the PDF generated from this PR.
> Remove authors from the paper until we are ready to add them

- main.tex
Rename 'Permutation' to 'Exchange'. I noticed that the rule is called the "exchange" rule in [this Wikipedia article](https://en.wikipedia.org/wiki/Structural_rule). But I also see it called "permutation" in [this other Wikipedia article](https://en.wikipedia.org/wiki/Sequent_calculus). So idk.
Whichever we pick, it should be consistent with the other rules. Our other structural rule is called "Weaken" (a verb), so this rule should be called either "Exchange" or "Permute", but not "Permutation".
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-exchange.pdf) is a link to the PDF generated from this PR.
> Rename 'Permutation' to 'Exchange'

- main.tex
Add the beginning of an abstract so the paper can start taking shape. I know it's early, but it helps me to see some words in the document. 😛 
Even though "delimited effects" is written in the abstract, it's still intended to be just a temporary placeholder until we come up with the real name.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-abstract.pdf) is a link to the PDF generated from this PR.
> Add the beginning of an abstract

- .gitignore
- Makefile
- deploy.sh
Add Coq compilation step to CI. Now the build will fail if the math is wrong!
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-ci-coq.pdf) is a link to the PDF generated from this PR.
> Add Coq compilation step to CI

- formalization/definitions.v
Improve the consistency of the Coq script. The main change is to be consistent about naming:
- Identifiers start with `i`.
- Types start with `t`.
- Terms start with `e` (for _expression_).
- Contexts start with `c`.
- Typing rules start with `a` (for _ascription_).
Also, all non-required type annotations were removed for brevity.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-style.pdf) is a link to the PDF generated from this PR.
> Improve the consistency of the Coq script

- formalization/definitions.v
Consistently use the custom Coq notation. Now the custom notation is used everywhere.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-notation.pdf) is a link to the PDF generated from this PR.
> Consistently use the custom Coq notation

- main.tex
Introduce a well-formedness judgment on operation types. This fixes https://github.com/stepchowfun/delimited-effects/issues/31.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-op-wellformed.pdf) is a link to the PDF generated from this PR.
> Introduce well-formedness judgment on operation types

- main.tex
Simplify the syntax and re-order the macros to match the order in which they appear in the syntax figure.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-syntax.pdf) is a link to the PDF generated from this PR.
> Simplify the syntax

- formalization/syntax.v
- formalization/typingRules.v
If you prefer, we can keep oplus as the symbol for extending a context.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-datatype-for-context.pdf) is a link to the PDF generated from this PR.
> Formalize context with a datatype

- main.tex
Remove some unused macros, rename some syntactic constructs for consistency, rename some figures, reorder some figures, copyedit the syntax exposition to reflect the notational conveniences currently in use, and fix an issue with `T-Application`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-syntax-polish.pdf) is a link to the PDF generated from this PR.
> Clarify the syntax

- formalization/syntax.v
I added our syntax to the coq formalization and moved notation and definition statements to the bottom of the syntax file. Todo: define the notation for the new syntax.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-formalize-syntax-coq.pdf) is a link to the PDF generated from this PR.
> Formalize our syntax in coq

- deploy.sh
Download the `coqc` binary from S3 instead of installing it with `apt-get`. This allows us to use Coq 8.6 instead of 8.4.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coqc.pdf) is a link to the PDF generated from this PR.
> Download the coqc binary from S3

- formalization/examples.v
- formalization/syntax.v
Parameterize the types of ids with phantom types in order to differentiate between each type of id (effect variable, type variable, etc).
I tried to get the `@` notation to work, but couldn't. It's commented out for now and I'm using `makeId` directly.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-phantom-types.pdf) is a link to the PDF generated from this PR.
> [coq] Add phantom types to ids

- main.tex
Remove the occurs check in `T-Provide`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-occurs-check.pdf) is a link to the PDF generated from this PR.
> Remove the occurs check in T-Provide

- main.tex
Add kinding rules.
Todo (in future PRs?):
- Update `T-Effect` and `T-Provide` (and remove the deprecated macros)
- Add type-equivalence rules
- Update the effect row preorder
- Update the "Operation type compatibility" figure
- Update the "Operation type well-formedness" figure
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kinds.pdf) is a link to the PDF generated from this PR.
> Add kinding rules

- main.tex
Update the well-formedness rule to work with schemes. Also add a check to the effect rule to make sure that the type of the operation has kind `*`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-well-formed.pdf) is a link to the PDF generated from this PR.
> Fix well-formedness rules and T-Effect

- main.tex
Rename some syntax, especially term application forms.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-application-by-name-or-value.pdf) is a link to the PDF generated from this PR.
> Rename some syntax, especially term application forms

- main.tex
Simplify the effect syntax.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-simplify-effect-syntax.pdf) is a link to the PDF generated from this PR.
> Simplify the effect syntax

- main.tex
Use a more uniform syntax for the two forms of application.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-application-syntax.pdf) is a link to the PDF generated from this PR.
> Use a more uniform syntax for the two forms of application

- .dockerignore
- .travis.yml
- Makefile
- deploy.sh
- docker/Dockerfile-build
- docker/Dockerfile-deps
Set up Docker build infrastructure for building the PDF, typechecking the Coq scripts, and linting. This will reduce the build time by approximately 1m.
Unfortunately, builds are still pretty slow (~6m) due to the time spent downloading the Docker image (3 GB!). But at least this gives us the option of optimizing the Docker image later.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-docker.pdf) is a link to the PDF generated from this PR.
> Set up Docker build infrastructure

- main.tex
Introduce subtyping. This will probably require a little more thought, but here is a first pass.
For simplicity, I also temporarily removed the `using` construct. We can add it back later once we have more solid foundations.
Hopefully after this we can close https://github.com/stepchowfun/delimited-effects/issues/62 and https://github.com/stepchowfun/delimited-effects/issues/77.
> Introduce subtyping

- main.tex
Remove deprecated macros.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-deprecated-macros.pdf) is a link to the PDF generated from this PR.
> Remove deprecated macros

- formalization/syntax.v
Put `termId` before `schemeId` (and likewise for `eid` and `sid`). I think this order makes more sense. I can't remember why we had it the other way before.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-reorder-ids.pdf) is a link to the PDF generated from this PR.
> Put termId before schemeId

- formalization/syntax.v
- main.tex
Make the LaTeX macros and Coq constructors match.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-constructor-names.pdf) is a link to the PDF generated from this PR.
> Make the LaTeX macros and Coq constructors match

- formalization/judgments.v
- main.tex
Several of the rules in the paper were incorrect. This PR fixes them (to the best of my knowledge) and formalizes them in Coq. Later we will prove that these rules capture "set-like" behavior.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-row-subsumption.pdf) is a link to the PDF generated from this PR.
> Finish the rules for effect row subsumption

- Makefile
- formalization/judgments.v
- formalization/subsumption.v
- formalization/syntax.v
- main.tex
Formalize in Coq the correctness proposition for effect row subsumption:
```coq
Theorem subsumptionCorrect :
forall r1 r2, (
forall s1,
rowContains r1 s1 ->
exists s2,
(schemeEq s1 s2 /\ rowContains r2 s2)
) <->
subsumes r1 r2.
```
Let's try to prove this theorem!
Also I updated the row subsumption rules in both LaTeX and Coq:
- I removed `E-RightAssociativity` because it can be recovered from a combination of the other associativity rule and exchange.
- I removed `E-RightContraction` because `E-Weakening` already generalizes it.
- I replaced `E-LeftIdentity` and `E-RightIdentity` with a unified `E-Identity` rule.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subsumption-correctness-proposition.pdf) is a link to the PDF generated from this PR.
> Formalize in Coq the correctness proposition for effect row subsumption

- formalization/judgments.v
Formalize the subtyping judgments in coq
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subtyping-judgements.pdf) is a link to the PDF generated from this PR.
> Add subtyping judgements

- formalization/judgments.v
- formalization/subsumption.v
Our first formally verified result: effect row subsumption implies containment up to effect row equivalence. The proof relies only on the fact that effect row equivalence is a preorder. It doesn't even require it to be an equivalence relation. Also, the proof will not need to be changed when we add the remaining rules for effect row equivalence.
The proof uses the following definition of containment:
```coq
Definition containment r1 r2 :=
forall s1,
rowContains r1 s1 ->
exists s2,
(schemeEq s1 s2 /\ rowContains r2 s2).
```
@ewang12 experimented with an alternate definition where the existential quantifier is commuted with the `rowContains` hypothesis:
```coq
Definition containment r1 r2 :=
forall s1,
exists s2,
rowContains r1 s1 ->
(schemeEq s1 s2 /\ rowContains r2 s2).
```
This …
> Prove that effect row subsumption implies containment up to effect row equivalence

- main.tex
Fix some typos in the typing rules (caught by Esther).
@ewang12 were there any others?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-typos.pdf) is a link to the PDF generated from this PR.
> Fix some typos in the typing rules (caught by Esther)

- formalization/judgments.v
Formalize kind equivalence in Coq.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kind-equivalence.pdf) is a link to the PDF generated from this PR.
> Formalize kind equivalence

- formalization/judgments.v
- formalization/subsumption.v
- formalization/syntax.v
- main.tex
Remove scheme equivalence in favor of subtyping and turn kind equivalence into subkinding.
Also:
- Many things were renamed and reordered to improve consistency.
- I removed `E-Subsumption` and `E-Contraction`, replacing both with `R-Union`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subtyping-and-subkinding.pdf) is a link to the PDF generated from this PR.
> Remove scheme equivalence in favor of subtyping and turn kind equivalence into subkinding

- formalization/judgments.v
- formalization/subsumption.v
- main.tex
Remove axioms `rRefl` and `rAssoc` and add them back as theorems.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subsumption-metatheory.pdf) is a link to the PDF generated from this PR.
> Remove axioms rRefl and rAssoc and add them back as theorems

- formalization/judgments.v
- formalization/subsumption.v
- formalization/syntax.v
- main.tex
Inline effect row subsumption into the subtyping rules. I also did a big refactoring to rename "scheme" to "type" everywhere. These two changes are separate commits.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subtyping-rows.pdf) is a link to the PDF generated from this PR.
> Inline effect row subsumption into the subtyping rules

- formalization/judgments.v
- formalization/subsumption.v
- main.tex
Merge the effect row subsumptions rules into the subtyping rules and re-prove everything.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-subsumption.pdf) is a link to the PDF generated from this PR.
> Merge the effect row subsumptions rules into the subtyping rules

- formalization/judgments.v
- formalization/syntax.v
Formalize the kinding rules, with one TODO to be completed when we have defined substitution on kinds. I also did minor cosmetic surgery on the `lookupEVar` and `lookupTVar` functions.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-kinding-rules.pdf) is a link to the PDF generated from this PR.
> Formalize the kinding rules

- formalization/subtyping.v
Refactor some proofs to explicitly give names to hypotheses.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-intro-patterns.pdf) is a link to the PDF generated from this PR.
> Refactor some proofs to explicitly give names to hypotheses

- formalization/helpers.v
- formalization/judgments.v
Updated the occurs check and the substitution helpers to recurse into rows and kinds as well as types. Also renamed some variables: type variables are consistently named `a`, and term variables are named `x`. Polymorphic identities are called `id`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-helpers.pdf) is a link to the PDF generated from this PR.
> Fully recurse on types in helpers

- formalization/helpers.v
- formalization/judgments.v
Implement `freeTVarsInX` for relevant syntactic categories `X`. I also removed `eqId` in favor of `eqIdDec` and cleaned up the indentation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-free-tvars.pdf) is a link to the PDF generated from this PR.
> Implement freeTVarsInX for relevant syntactic categories X

- main.tex
Add beta reduction and update `ST-TypeApplication` to check for equivalence of the parameters. This will relate `Num Int` and `Num ((\a : * . a) Int)` under subtyping.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-beta-reduction-subtyping.pdf) is a link to the PDF generated from this PR.
> Add beta reduction to subtyping

- formalization/judgments.v
I don't really like that `htProvide` uses both `subtype` and `rowContains`, but `~ subtype` doesn't work because of Coq's restriction requiring strictly positive occurrences of `subtype`. What do you think?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-htprovide.pdf) is a link to the PDF generated from this PR.
> Make htProvide remove the provided effect

- formalization/judgments.v
- formalization/subtyping.v
- main.tex
Replace the `ST-Exchange` axiom with `ST-WeakenRight`, and add `ST-Exchange` back as a theorem. Do you think we should do this, or keep `ST-Exchange` as an axiom?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-weaken-right.pdf) is a link to the PDF generated from this PR.
> Replace ST-Exchange with ST-WeakenRight

- formalization/helpers.v
- formalization/judgments.v
- paper/main.tex
Allow variable shadowing and simplify the typing rules.
When [formalizing the STLC](https://github.com/stepchowfun/coq-fun/blob/master/coq/stlc.v), I realized it's actually more natural to allow variable shadowing than to forbid it. Previously our typing rules had to check that new variables being introduced into the context (e.g., by `T-Abstraction`) were not already in the context, but no other paper seems to do that. It seems more natural to be able to add any variable to the context at any time, and just have a smarter lookup function in rules like `T-Variable` which will select the most "recent" occurrence. I've seen this in other papers. This corresponds exactly to how we are formalizing it in Coq, and it also makes the typing rules simpler.
I also reordered the premises in …
> Allow variable shadowing and simplify the typing rules

- paper/main.tex
- Delete `T-Subsumption` because it's already (necessarily) inlined into the typing rules for applications.
- Make `K-Unit` the same color as `T-Unit` (blue, because it's only temporary? but maybe we should keep it permanently...).
- Add subtyping rule (`ST-Unit`) for the unit type, just like the one for arrows (not sure how we missed this).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-small-fixes.pdf) is a link to the PDF generated from this PR.
> Various unrelated fixes

- paper/main.tex
Clean up some stuff:
- Remove vestigial `chktex` comments
- Change the syntax for the two forms of application to be more palatable (what do you think)
- Change all the red stuff back to black (it seems premature since we have stuff to fix first)
- Make the "Draft" watermark lighter so it's less obnoxious
- Move the code example to a new "Overview" section
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-cleanup.pdf) is a link to the PDF generated from this PR.
> Clean up some stuff

- formalization/judgments.v
- formalization/syntax.v
- paper/main.tex
Remove application-by-value as a syntactic construct. It can be an ordinary value instead. This would be the type of that value:
```
strict : forall t1, t2, e1, e2, e3 .
(t1 ! ∅ -> t2 ! e2) ! e3 ->
t1 ! e1 -> t2 ! e1, e2, e3
```
**Note 1:** I think this function is impossible to define in our system, so it has to be a "built-in" value (e.g., provided by a standard library, just like Haskell's `seq`—which is not definable in Haskell).
**Note 2:** We can define Haskell's `seq` in terms of `strict`: `seq a b = strict (\x -> b) a`. I think the other direction is impossible: we can't define `strict` in terms of `seq`. So, `strict` is strictly more general than `seq`, pun intended.
Motivation:
- Simpler (and more conventional) syntax—finally we only have one form of application!
- Simpler type …
> Remove application by value

- formalization/judgments.v
- formalization/subtyping.v
- paper/main.tex
Simplify the system by removing `ST-Singleton` in favor of `ST-Reflexivity`.
This simplifies our only theorem so far from this:
To this much nicer theorem:
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-st-singleton.pdf) is a link to the PDF generated from this PR.
> Remove ST-Singleton

- formalization/judgments.v
- formalization/syntax.v
- paper/main.tex
This PR also adds effect rows back to the syntax for types.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-user-effects.pdf) is a link to the PDF generated from this PR.
> Remove support for user-defined effects

- paper/main.tex
In the current syntax, epsilon represents a single effect rather than an effect row.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-deprecate-rows.pdf) is a link to the PDF generated from this PR.
> Remove usages of epsilon for effect rows

- paper/main.tex
Delete the operation type well-formedness figure for now.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-op-type-wellformedness.pdf) is a link to the PDF generated from this PR.
> Delete the operation type well-formedness figure for now

- paper/main.tex
Remove the operation name from the effect well-formedness judgment.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-well-formedness.pdf) is a link to the PDF generated from this PR.
> Remove the operation name from the effect well-formedness judgment

- paper/main.tex
Introduce synonyms for `\tau` to enhance readability. This PR closes https://github.com/stepchowfun/delimited-effects/issues/161.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-type-symbols.pdf) is a link to the PDF generated from this PR.
> Introduce synonyms for \tau to enhance readability

- paper/main.tex
Don't allow (co)effects on abstractions in the application rules. If you want to apply a function with (co)effects, you will have to use (`co`)`strict`.
Motivation: previously we had an unnatural asymmetry. The typing rule for application would refuse to propagate (co)effects on the argument type (insisting that the type of the given argument is a subtype of the expected argument type), but it would propagate (co)effects on the function type. Now all propagation for applications is handled by `strict` (and analogously for type application and `costrict`).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-applications.pdf) is a link to the PDF generated from this PR.
> Don't allow (co)effects on abstractions in the application rules

- paper/main.tex
Rearrange the type symbols to reflect the order in the syntax.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-type-symbol-ordering.pdf) is a link to the PDF generated from this PR.
> Rearrange the type symbols to reflect the order in the syntax

- paper/main.tex
Move row difference from the metalanguage to the object language. This is needed to give types to terms involving `provide`, which is crucial to our system.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-row-difference.pdf) is a link to the PDF generated from this PR.
> Move row difference from the metalanguage to the object language

- paper/main.tex
Happy to rename the rules to something more descriptive.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-distribute-diff-over-union.pdf) is a link to the PDF generated from this PR.
> Add subtyping rules to distribute difference over union

- paper/main.tex
Simplify subtyping by only defining the preorder for (co)effect rows. This closes https://github.com/stepchowfun/delimited-effects/issues/96.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-simplify-subtyping.pdf) is a link to the PDF generated from this PR.
> Simplify subtyping by only defining the preorder for (co)effect rows

- paper/main.tex
Eliminate kinds, and have distinct syntactic categories for proper types, embellished types, and (co)effect rows. What do you think?
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-eliminate-kinds.pdf) is a link to the PDF generated from this PR.
> Eliminate kinds

- paper/main.tex
Instead of using `\sigma` to represent an embellished type, have the full syntactical representation of an embellished type everywhere.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-embellished.pdf) is a link to the PDF generated from this PR.
> Inline embellished types

- paper/main.tex
1. Rename `T-Application` to `T-ApplicationByName`
2. Introduce `T-ApplicationByValue`
3. Remove stacking for all the premises in the typing rules to make the figure fit on the page
4. Delete the `Effect and coeffect propagation` section
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-application-by-value.pdf) is a link to the PDF generated from this PR.
> Make a typing rule for application by value

- paper/main.tex
Type application should expect a proper type for the argument, not an embellished type.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-type-application.pdf) is a link to the PDF generated from this PR.
> Fix a bug in the syntax for type application

- paper/main.tex
Rename `R-DifferenceUnion` to `R-DifferenceDomination`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-domination.pdf) is a link to the PDF generated from this PR.
> Rename R-DifferenceUnion to R-DifferenceDomination

- paper/main.tex
Do not allow coeffects in quantified types. Coeffect rows cannot be merged, and we need to not allow (row-)quantified types to have coeffects in order to ensure that this never happens.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-quantified-types.pdf) is a link to the PDF generated from this PR.
> Do not allow coeffects in quantified types

- formalization/syntax.v
Remove coeffects from the formalization. I also renamed `properType` to `type` in order to match the paper.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-coeffects.pdf) is a link to the PDF generated from this PR.
> Remove coeffects from the formalization

- formalization/syntax.v
Remove `coprovide` from the syntax in the formalization. Looks like we missed this.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-remove-coprovide.pdf) is a link to the PDF generated from this PR.
> Remove coprovide from the syntax in the formalization

- implementation/src/Lib.hs
Add a missing case to the `Row` data type.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-rvar.pdf) is a link to the PDF generated from this PR.
> Add a missing case to the Row data type

- implementation/test/Spec.hs
Add a complete spec for `rowEquiv`. This spec is complete in the sense that it fully captures the behavior we want this equivalence relation to have, so there are no more tests to write.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-row-equiv-spec.pdf) is a link to the PDF generated from this PR.
> Add a complete spec for `rowEquiv`

- implementation/test/Spec.hs
We could use [Generic.Random.Generic](https://hackage.haskell.org/package/generic-random-0.3.0.0/docs/Generic-Random-Generic.html) from the `generic-random` package to clean it up even more, but that might be overkill.
> Clean up the Arbitrary Context instance

- implementation/src/Lib.hs
- implementation/test/Spec.hs
Implement `shrink` for all the `Arbitrary` instances. This will allow QuickCheck to generate smaller counterexamples.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-shrink.pdf) is a link to the PDF generated from this PR.
> Implement shrink for all the Arbitrary instances

- Makefile
Add line length checking for Haskell source files (like we have for other types of source files).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-lint.pdf) is a link to the PDF generated from this PR.
> Add line length checking for Haskell source files

- implementation/test/Spec.hs
Shrink the first 8 elements of the context streams to make the counterexamples easier to read.
Falsifiable (after 3 tests and 6 shrinks):
Context {getV = RSingleton EffectE, getW = RVar VariableX, getX = REmpty, getY = RVar VariableZ, getZ = RVar VariableV} <:> Context {getV = RSingleton EffectE, getW = RVar VariableV, getX = RSingleton EffectB, getY = REmpty, getZ = RDifference (RVar VariableX) (RVar VariableW)} <:> Context {getV = RUnion (RSingleton EffectD) (RDifference (RVar VariableW) (RUnion (RDifference (RUnion (RVar VariableW) (RVar VariableX)) REmpty) (RSingleton EffectD))), getW = REmpty, getX = RDifference (RVar VariableX) (RUnion (RSingleton EffectB) (RSingleton EffectC)), getY = RSingleton EffectE, getZ = REmpty} <:> Context {getV = RDifference (RVar VariableV) (RDifference …
> Shrink the first 8 elements of the context streams

- scripts/Dockerfile
Update the Dockerfile to install the version of GHC used by the implementation.
> Build using a Docker image that has GHC preinstalled

- .travis.yml
This will speed up builds by caching the package dependencies of the implementation.
> Cache the .stack-work directory

- implementation/src/Lib.hs
- implementation/test/Spec.hs
Define row equivalence as equality of normal forms.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-normalize.pdf) is a link to the PDF generated from this PR.
> Define row equivalence as equality of normal forms

- Makefile
- implementation/src/Lib.hs
Turn on pedantic mode for Haskell and fix all the errors.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-pedantic.pdf) is a link to the PDF generated from this PR.
> Turn on pedantic mode for Haskell and fix all the errors

- Makefile
- implementation/src/Lib.hs
- implementation/test/Spec.hs
Implement effect row equivalence decision procedure, based on:
- A great idea by @ewang12 to embed the effect rows into propositional logic (equivalent to adding a complement operation) and check for equivalence in that language
- An experiment by me to use a Boolean ring for the propositional logic language and convert the formulas into algebraic normal form for easy comparison
I noticed that our test was wrong (it would fail sometimes when it should have passed), so I replaced the broken spec with two new ones.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-normalize.pdf) is a link to the PDF generated from this PR.
> Implement effect row equivalence

- paper/main.tex
I recently watched [this talk](https://www.youtube.com/watch?v=dCuZkaaou0Q) by Guy Steele, which discusses notation in CS papers. Apparently Guy found dozens of different notations in use for substitution, and we are using one of the more ambiguous ones (because `\mapsto` is also used for map update). So this PR switches it to use the more popular `e[e/x]` notation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-notation.pdf) is a link to the PDF generated from this PR.
> Use e[e/x] notation for substitution as recommended by Guy Steele

- paper/main.tex
Reintroduce `using` (with an experimental new syntax).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-using.pdf) is a link to the PDF generated from this PR.
> Reintroduce using

- paper/main.tex
Delete the row equivalence parts of the paper. The plan is to replace this with a more general subtyping relation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-delete-row-equivalence.pdf) is a link to the PDF generated from this PR.
> Delete the row equivalence parts of the paper

- paper/main.tex
Remove the introduction text, because it was distracting and not well-written.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-delete-introduction.pdf) is a link to the PDF generated from this PR.
> Remove the introduction text

- paper/main.tex
Reintroduce subtyping. We will define the "subrow" relation in a follow-up PR.
> Reintroduce subtyping

- implementation/src/Lib.hs
- implementation/test/Spec.hs
Implement the subrow relation in Haskell (replacing row equivalence).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-implementation.pdf) is a link to the PDF generated from this PR.
> Implement the subrow relation in Haskell

- implementation/implementation.cabal
- implementation/src/Lib.hs
- implementation/src/Subrow.hs
- implementation/src/Syntax.hs
- implementation/test/LibSpec.hs
- implementation/test/SubrowSpec.hs
- implementation/test/SyntaxSpec.hs
Add data types for syntax to the Haskell implementation.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-implementation-syntax.pdf) is a link to the PDF generated from this PR.
> Add data types for syntax to the Haskell implementation

- implementation/implementation.cabal
- implementation/src/Lib.hs
- implementation/src/Syntax.hs
- implementation/test/SubrowSpec.hs
- implementation/test/SyntaxSpec.hs
- implementation/test/Types.hs
Add specs for `contextLookup` and `effectMapLookup`.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-syntax-specs.pdf) is a link to the PDF generated from this PR.
> Add specs for contextLookup and effectMapLookup

- implementation/test/SyntaxSpec.hs
Align function arrows in type annotations to the double colon.
> Align arrows to double colon in type annotations

- implementation/implementation.cabal
- implementation/src/Lib.hs
- implementation/src/Subtype.hs
- implementation/test/LibSpec.hs
- implementation/test/SubrowSpec.hs
- implementation/test/SubtypeSpec.hs
- implementation/test/SyntaxSpec.hs
- paper/main.tex
Fix subtyping in the paper and implement it in Haskell.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subtype.pdf) is a link to the PDF generated from this PR.
> Fix subtyping in the paper and implement it in Haskell

- implementation/src/Inference.hs
- implementation/src/Subtype.hs
- implementation/test/InferenceSpec.hs
- implementation/test/SubtypeSpec.hs
- paper/main.tex
Remove the subrow part of the subtype relation, because there is already a separate subrow relation. This change applies to the Haskell implementation and the LaTeX writeup, but not the Coq scripts because we haven't defined this relation there.
> Remove the subrow part of the subtype relation

- paper/main.tex
In the subtyping section, we define the subrow relation as a boolean equation, and prove its logical equivalence to set inclusion.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-subrow-writeup.pdf) is a link to the PDF generated from this PR.
> Write subtyping section

- implementation/src/Inference.hs
- implementation/src/Lib.hs
- implementation/test/InferenceSpec.hs
Refactor the inference algorithm into 4 mutually recursive functions. This is a more faithful extension of the traditional bidirectional type inference algorithm. I think it will be easier to formalize this way (both in LaTeX and in Coq). Also, now there are no functions which return more things than necessary (for example, in the previous version, calling `infer` in inference mode would return unmodified the type/row that you passed in).
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-inference-refactor.pdf) is a link to the PDF generated from this PR.
> Refactor the bidirectional inference algorithm into 4 mutually recursive functions

- paper/main.tex
With the previous typing rule, recursion was implicitly baked into the type system. For instance, we could type the expression
```
provide Log / []
with
log = \s -> log s
in
...
```
After this change, if the effect being provided occurs in the type of the implementation, but not in the `using` list, the `provide` will not be well-typed. This change imposes no significant new restrictions because the programmer can still reuse the implementation currently being provided by storing the implementation in a variable outside the provide.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-fix-substitution-provide.pdf) is a link to the PDF generated from this PR.
> Prevent recursion in provide

- implementation/src/Inference.hs
- implementation/src/Syntax.hs
- implementation/test/InferenceSpec.hs
- implementation/test/SyntaxSpec.hs
- paper/main.tex
Let the effect map map an effect to a variable rather than an embellished type.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-map.pdf) is a link to the PDF generated from this PR.
> Let the effect map map an effect to a variable rather than an embellished type

- paper/main.tex
Use `\Sigma` instead of `E` for the effect map. This matches Pretnar's [tutorial](http://www.eff-lang.org/handlers-tutorial.pdf) and looks a little nicer IMO.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-sigma.pdf) is a link to the PDF generated from this PR.
> Use \Sigma instead of E for the effect map

- paper/main.tex
Remove the confusing subscripts from the `\varnothing` constructors. Hopefully things will be clear from context (no pun intended). We'll keep the separate macros in case we later discover an elegant way to syntactically distinguish between these constructors.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-varnothing.pdf) is a link to the PDF generated from this PR.
> Remove the confusing subscripts from the \varnothing constructors

- paper/main.tex
Add a well-formedness figure for effect contexts. I am not sure if we want this, but it seems incomplete without it.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-wfc.pdf) is a link to the PDF generated from this PR.
> Add a well-formedness figure for effect contexts

- formalization/syntax.v
- implementation/implementation.cabal
- implementation/src/Error.hs
- implementation/src/Inference.hs
- implementation/src/Lib.hs
- implementation/src/Syntax.hs
- implementation/test/ErrorSpec.hs
- implementation/test/InferenceSpec.hs
- implementation/test/LibSpec.hs
- paper/main.tex
Document the inference algorithm in the paper. The algorithm didn't fit cleanly on one page, so I split it into two columns.
When writing up the algorithm, I also discovered and fixed three problems:
1. In the Haskell implementation for `T-Handle`, we were in inference mode for the type of the user-supplied implementation of the operation. This was not wrong per se, but it was undesirable because we were unable to take advantage of information we already know (the expected type of the operation). The reason we were in inference mode and not checking mode is because we wanted to allow for subtyping; so the algorithm was a) infer the type, b) check that it is a subtype of the expected type. But, luckily, the subsumption rules already handle subtyping (in this case, `T-Subsumption 3-5`). So …
> Document the inference algorithm in the paper

- paper/main.tex
Simplify the context well-formedness figure and make some small syntax improvements.
Note: the well-formedness figure simplification was @esdrw's idea.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-well-formedness.pdf) is a link to the PDF generated from this PR.
> Simplify the context well-formedness figure and make some small syntax improvements

- formalization/syntax.v
- paper/main.tex
Introduce hoisting. A few highlights:
1. Super unexpected result: by propagating effects inward instead of outward, we don't need row difference anymore! That means we don't need the Boolean ring algorithm! To compare two effect rows, we can just sort and unique them. We can even bring back the old subrow axioms that we proved correct in Coq. Goodbye exponential-time algorithm!
2. Function parameters can now have effects—and amazingly we still don't need two forms of application.
3. We are now always in checking mode for the effect row. Synthesis mode for effects has been removed. This is crucial: each rule needs to know which effects are allowed in the current scope so it can decide whether or not hoisting is needed. We still have both checking and synthesis for types, however.
4. Type …
> Introduce hoisting

- formalization/syntax.v
Remove the type and effect row from emExtend in the Coq script.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-effect-map.pdf) is a link to the PDF generated from this PR.
> Remove the type and effect row from emExtend in the Coq script

- .gitignore
- Makefile
Set up the Coq project properly. Now, if you want to add a new Coq file, all you have to do is create the file. The `Makefile` automatically:
1. Finds all the Coq files
2. Determines all their dependencies
3. Builds them incrementally (only the ones that need to be rebuilt)
I also tested this to make sure it supports Coq files importing other Coq files from nested subdirectories.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coq-project.pdf) is a link to the PDF generated from this PR.
> Set up the Coq project properly

- paper/main.tex
To make computations more meaningful, replace the unit value and its corresponding type with true and false, and the bool type.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-unit-to-bool.pdf) is a link to the PDF generated from this PR.
> Replace unit with boolean

- _CoqProject
Add a `_CoqProject` file.
In https://github.com/stepchowfun/delimited-effects/pull/260, I updated the `Makefile` to support automatic discovery of Coq files. Even though the build system supported subdirectories, it seemed CoqIDE didn't.
After hours of debugging and Googling, I finally found a solution: this `_CoqProject` file. It is not a full `_CoqProject` since it does not explicitly enumerate the `.v` Coq files (by design, so we don't have to maintain it). This is just enough to get CoqIDE to set up its paths correctly such that nested subdirectories work. I'm using this successfully in https://github.com/stepchowfun/coq-fun which has some non-flat directory structure.
Note that our `make` system automatically generates (and subsequently deletes) a _different_ `_CoqProject` file …
> Add a _CoqProject file

- Makefile
- _CoqProject
Fix the `_CoqProject` setup. I just blindly copied the file from my `coq-fun` repo, but I forgot that the Coq directory is called `formalization` instead of `coq`. Doh. I actually tested it this time in CoqIDE.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-coqproject.pdf) is a link to the PDF generated from this PR.
> Fix the _CoqProject setup

- Makefile
1. Rename `CoqMakefile` to `Makefile.coq` to be consistent with Adam Chlipala/CPDT (why not ~)
2. Update the Makefile to clean up some temporary files even when the build fails.
Regarding (2), the files in question are `Makefile.coq` and `_CoqProjectFull`. These are normally created and deleted automatically when building the formalization. But when the build fails, they are left behind. We could add them to the `.gitignore` or just make sure to always clean them up even when the build fails. This PR implements the latter.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-make-fail.pdf) is a link to the PDF generated from this PR.
> Update the Makefile to clean up some temporary files even when the build fails

- formalization/Syntax.v
Add a Boolean primitive type to the Coq formalization. @esdrw is doing the same for the Haskell implementation in https://github.com/stepchowfun/delimited-effects/pull/267.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-bool.pdf) is a link to the PDF generated from this PR.
> Add a Boolean primitive type to the Coq formalization

- Makefile
Move the implementation tests to a separate make target. Now, just running `make` does not run the tests (which makes it really fast if there is nothing to build). You can run `make test` to run the tests. The CI system is configured to do both, of course.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-test-target.pdf) is a link to the PDF generated from this PR.
> Move the implementation tests to a separate make target

- formalization/Syntax.v
- paper/main.tex
Add universal types to the LaTeX writeup and the Coq formalization. The Haskell implementation will come later.
This required a fairly large refactoring of the hoisting machinery in the inference rules, but I think it actually made the rules simpler in the end. I also removed Booleans, because they can now be Church-encoded.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-system-f.pdf) is a link to the PDF generated from this PR.
> Add universal types

- .travis.yml
Add some simple logic to print a message every minute to prevent Travis from thinking the build is stuck.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-travis-wait.pdf) is a link to the PDF generated from this PR.
> Prevent Travis from killing the build

- paper/main.tex
Add kinds (for use later), and effect rules for user-defined monomorphic effects.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-recursive-types-version.pdf) is a link to the PDF generated from this PR.
> Formalize monomorphic effects as types

- paper/main.tex
Remove a useless macro.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-em-map.pdf) is a link to the PDF generated from this PR.
> Remove a useless macro

- paper/main.tex
Remove another useless macro.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-effect-macro.pdf) is a link to the PDF generated from this PR.
> Remove another useless macro

- implementation/src/Lib.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
- implementation/test/SyntaxSpec.hs
Before, we were using strings for term and type variables. This meant our property checks were mostly useless because QuickCheck would generate arbitrary strings in the specs rather than using the set of term and type variable strings that we were using in the arbitrary instances of other datatypes.
Here we introduce new types for term and type variables, so that we can define arbitrary instances that will be used by both QuickCheck as well as other arbitrary instances.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-types-for-variables.pdf) is a link to the PDF generated from this PR.
> Introduce separate types for term and type variables

- paper/main.tex
Add a declarative version of the type system to make the metatheory simpler. In particular, we hope that this will make the soundness proof easier.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-declarative-typing.pdf) is a link to the PDF generated from this PR.
> Add a declarative version of the type system

- paper/main.tex
Delete the declarative version of the type system because it would lead to non-deterministic choices of hoisted term sets. The inference algorithm will be the specification.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-inference.pdf) is a link to the PDF generated from this PR.
> Delete the declarative version of the type system

- paper/main.tex
Introduce syntactic sugar for either checking or inference mode. I'm not sure if we'll keep this, but for now it's convenient since it allows the typing rules to fit on one page.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-updown.pdf) is a link to the PDF generated from this PR.
> Introduce syntactic sugar for either checking or inference mode

- paper/main.tex
Document some conventions in the typing rules.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-caveats.pdf) is a link to the PDF generated from this PR.
> Document some conventions

- paper/main.tex
Add syntax coloring for types.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-color-type.pdf) is a link to the PDF generated from this PR.
> Add syntax coloring for types

- paper/main.tex
Update some of the syntax to match the new hoisting strategy.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-hoisted-terms.pdf) is a link to the PDF generated from this PR.
> Update some of the syntax to match the new hoisting strategy

- paper/main.tex
Move the syntax for hoisted term maps.
[Here](https://s3.amazonaws.com/stephan-misc/paper/branch-hoisted-terms.pdf) is a link to the PDF generated from this PR.
> Move the syntax for hoisted term maps

- formalization/Name.v
- formalization/Subrow.v
- formalization/Syntax.v
- formalization/Tactics.v
Use distinct types for term names and type names. I also updated the tactics library based on my experience in https://github.com/stepchowfun/coq-fun.
> Use distinct types for term names and type names

- formalization/Subrow.v
Implement some minor style tweaks:
- Alphabetize all quantified variables (is this a good convention?).
- In the `subrow` rules, quantifiers appear on their own line—except for `rsEmpty`. This PR updates `rsEmpty` to be consistent with the rest.
> Implement some minor style tweaks

- implementation/stack.yaml
- scripts/Dockerfile
Install Ruby explicitly in the base image. Somehow this is already installed (my guess is that Stack installed it), so this is technically redundant. But let's not depend on that.
> Install Ruby explicitly in the base image

- .gitignore
- Makefile
Update the `Makefile` to clean up files from Coq 8.7.1.
> Update the `Makefile` to clean up files from Coq 8.7.1

- Makefile
Fail if `Admitted` is found in proofs. Too extreme?
This is what it looks like when it fails:
> Fail if 'Admitted' is found in proofs

- Makefile
Make minor improvements to the `Makefile`:
- Do the `Admitted` check after the rest of linting so `make lint` is not useless when working on a partially-proven theorem.
- Collapse some of the `make` invocations in the `docker-build` target (but still ensure that `make clean` happens before the other targets).
> Make minor improvements to the Makefile

- .gitignore
- Makefile
- implementation/LICENSE
- implementation/implementation.cabal
Remove references to a nonexistent `.github` directory. We used to have a pull request template in there to instruct us how to link to the PDF from the branch build, but these days the deploy script automatically posts a link to that PDF in pull requests.
I also removed some other `.gitignore` paths (and analogous paths in the Makefile) that I believe are not used.
I updated the copyright years too.
> Remove references to a nonexistent '.github' directory

- paper/main.tex
- scripts/lint-tex.rb
Use ordinary type variables for tracking handlers instead of "effect variables". This simplifies things (we no longer need abstraction/application for effect variables, etc.).
> Use type variables for tracking handlers

- paper/main.tex
Improve the way `reflect` works and simplify some terminology (`reified term` → `witness`). The `reflect` change is small but has big consequences:
- We no longer need hoisting, because witnesses can come from lexical scope (except the ones which appear in rows).
- Type classes are more straightforward now. Previously, we had:
```haskell
add : ∀(a : *) (b : <Num a>) . (a -> a -> a) ! {b}
```
And now it's just:
```haskell
add : ∀(a : *) (b : <Num a>) . a -> a -> a
```
> Improve the way `reflect` works and simplify some terminology

- paper/main.tex
This PR is the result of me thinking really hard for 2 days about the limitations of the system.
- The main change of this PR: Previously, types were paired with effect rows almost everywhere (e.g., in the typing context, in arrow types, etc.), which made the whole system quite an eyesore (and also very intimidating). Now, <img width="32" alt="screenshot 2018-04-07 18 24 23" src="https://user-images.githubusercontent.com/796574/38461902-f4bca31e-3a90-11e8-8102-d29372cff1ed.png"> is just another type constructor. This construct (a type paired with a row) is called an "entangled" type, because the type is "entangled" with the witnesses in the row. I think this is a little more entertaining and suggestive than "embellished" type, but I have no strong opinion. There is a new kinding rule for …
> Have `t ! w` be an ordinary type constructor

- paper/main.tex
- paper/overview.tex
Use a less ambiguous example in the introduction. String concatenation is `+` in some languages and `++` in others, but integer addition is almost always `+`. I also removed a bind, because I'm not sure why it was there in the first place.
@esdrw
> Use a less ambiguous example

- paper/overview.tex
Previously, we had the following syntactic sugar for types:
> `K => T` means `forall t : K, T` where `t` does not occur in `T`.
But after thinking about it for a while, I think the only time you would ever quantify over a type and not use it (at the type level) is when that type is a witness (e.g., a type class instance or effect handler). For example:
<Monoid a> => a -> a -> a
So, I propose the following slightly more streamlined sugar instead:
> `T1 => T2` means `forall t : <T1> . T2` where `t` does not occur in `T2`.
Then the monoid example becomes:
Monoid a => a -> a -> a
The only difference is the lack of angle brackets `<>`.
@esdrw
> Simplify the syntactic sugar

- Makefile
- paper/main.tex
Don't show the date for non-acm builds and default to acm in CI. This basically means local work is in distraction-free mode, but the paper that is deployed in CI includes all the metadata.
> Don't show the date for non-acm builds and default to acm in CI

- paper/entanglement.tex
Change `T-Reflect` to return an entangled type. Unfortunately this is needed to make effect tracking work; without it, you could reflect an `IO` instance into a term, pass it to some distant part of the program, and reflect it back as a type variable to allow IO wherever you want.
@esdrw
> Change T-Reflect to return an entangled type

- formalization/SystemF/Name.v
Make the proof of `nameFresh` a little more straightforward.
> Make the proof of nameFresh a little more straightforward

- paper/calculus.tex
- paper/macros.tex
I feel like I hit a stroke of good luck this weekend. Another opportunity for simplification has presented itself: apparently we don't need singleton rows.
To recap, we previously had 4 things that can have the kind `row`:
- A type variable which stands for an unknown row
- The empty row
- The singleton row containing a single type variable of kind `witness`
- The union of two rows
Some recent developments have made singleton rows completely obsolete: rows are now fully abstract, with no internal structure. Note that:
- Type classes don't use rows at all
- Effects are polymorphic over entire rows and never refer to singletons:
```haskell
data IO e = IO (String ! e) (String -> () ! e)
```
Therefore, we should not even have singleton rows. We are left with:
- A type variable which stands …
> Delete the idea of singleton rows

- paper/calculus.tex
- paper/macros.tex
I took a 30m nap after merging https://github.com/stepchowfun/delimited-effects/pull/377 and then woke up to realize: we don't even need row union! So we used to have this:
```haskell
computation : forall (i1 : <IO e1>) (i2 : <Exception e2>) . Int ! e1 U e2
```
But I realized we can actually just have `IO` and `Exception` be instantiated to the same effect row `e`:
```haskell
computation : forall (i1 : <IO e>) (i2 : <Exception e>) . Int ! e
```
So, let's delete union! Now there are exactly two things which can be given kind `row`:
- A type variable standing for an unknown row
- The empty row
In fact, we probably shouldn't even call them "rows" anymore. I'll figure out a better name in a follow-up PR.
I deleted the entire "row subsumption" figure. Also, I deleted `T-Subsumption`, which …
> Delete the concept of row union

- paper/calculus.tex
- paper/macros.tex
- paper/main.tex
- scripts/lint-tex.rb
Improve some notation. Also, some new terminology:
So if `Monoid` is a type class...
```haskell
square : Monoid a => a -> a
square x = combine x x
```
...then `IO` is an "effect class":
```haskell
greet : IO e => () ! e
greet = printLine "Hello!"
```
...and `e` is now called an "effect", rather than a "row". Effect classes are predicates on effects, just as type classes are predicates on types.
@esdrw
> Improve some notation

- implementation/app/Main.hs
- implementation/implementation.cabal
- implementation/src/FSyntax.hs
- implementation/src/Inference.hs
- implementation/src/Lib.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
- implementation/test/FSyntaxSpec.hs
- implementation/test/InferenceSpec.hs
- implementation/test/LibSpec.hs
- paper/calculus.tex
Set up the scaffolding for an inference algorithm. I also created a much better `show` instance for terms/types than the default one. Previously:
```haskell
EAnno
(EAbs "f" (EAbs "g" (EAbs "x" (
EApp (EApp (EVar "f") (EVar "g")) (EVar "x")
))))
(TForAll "a" (TForAll "b" (TForAll "c" (
TArrow (TVar "a") (TArrow (TVar "b") (TVar "c"))
))))
```
Now:
```haskell
\f . \g . \x . f g x : forall a . forall b . forall c . a -> b -> c
```
I would use `λ`, `Λ`, and `∀`, but apparently Brittany doesn't support Unicode.
@esdrw
> Set up the scaffolding for an inference algorithm

- implementation/src/FSyntax.hs
- implementation/src/Inference.hs
- implementation/src/Syntax.hs
Improve the pretty printer by collecting variables in nested abstractions / foralls.
Before:
```haskell
\f . \g . \x . f g x : forall a . forall b . forall c . a -> b -> c
```
After:
```haskell
\f g x . f g x : forall a b c . a -> b -> c
```
@esdrw
> Improve the pretty printer

- paper/calculus.tex
- paper/macros.tex
Bring back row union. Without it, we have types that look like this:
```haskell
forall (e : row) (i1 : <Log e>) (i2 : <Exception e>) . () ! e
```
I thought about it for a while and realized: that's the type of a computation which does at most logging _OR_ exception throwing, but not both. It can't do both because in general handlers of `Log` or `Exception` don't let you choose `e`—they pick a fresh `e` for you. So you cannot pick two fresh type variables and expect them to be equal.
So, sadly, the type has to be:
```haskell
forall (e1 e2 : row) (i1 : <Log e1>) (i2 : <Exception e2>) . () ! e1, e2
```
That's an unfortunate mouthful. Some syntactic sugar is sorely needed.
Equally unfortunate is the fact that the moniker "effect classes" no longer makes sense.
@esdrw
> Bring back row union

- implementation/src/Inference.hs
- implementation/src/Syntax.hs
Refactor the pretty-printers. I got to (had to) use functional dependencies. :) I also tried implementing this with type families (associated types), but it was uglier. So fundeps it is!
The only observable change: I made the pretty printer group related arguments. Before:
```haskell
\(x : a) (y : b) (z : b) (w : a) . f
```
After:
```haskell
\(x : a) (y z : b) (w : a) . f
```
@esdrw
> Refactor the pretty-printers

- Makefile
- implementation/Setup.hs
- implementation/app/Main.hs
- implementation/src/Inference.hs
- implementation/src/Syntax.hs
- implementation/test/InferenceSpec.hs
- implementation/test/LexerSpec.hs
- implementation/test/LibSpec.hs
- implementation/test/ParserSpec.hs
- implementation/test/SyntaxSpec.hs
- scripts/Dockerfile
Switch from `brittany` to `hindent` for formatting Haskell. I think `brittany` produces better-looking output in some cases, but `hindent` is more consistent. Furthermore, `hindent` supports Unicode (so we can use symbols like `λ` in strings). Switching to `hindent` also allows us to remove some hacks in the Dockerfile.
I also made a small improvement to the `Makefile` that ensures file timestamps are not touched when running `make format-implementation` unless there are actual changes to be made. So that means running `make format-implementaiton` will not invalidate the build cache unless any files were actually affected.
@esdrw
> Switch from brittany to hindent

- .hindent.yaml
- Makefile
- implementation/app/Main.hs
- implementation/examples/test.g
- implementation/implementation.cabal
- implementation/src/Inference.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Implement a simple type inference algorithm for System F! Some examples from me using it in interactive mode:
```haskell
> \x . x : forall a . a -> a
λ(a : *) (x : a) . x
: ∀a . a -> a
> (\x . x : (forall a . a -> a) -> (forall b . b -> b)) (\y . y)
(λ(x : ∀a . a -> a) (b : *) . x b) λ(a : *) (y : a) . y
: ∀b . b -> b
> (\x y . x : forall a b . a -> b -> a) (\u v w . u (v w) : forall c d e . (d -> c) -> (e -> d) -> e -> c) (\z . z : forall f . f -> f)
λ(a b : *) . (λ(b a : *) . (λ(a b : *) (x : a) (y : b) . x) ∀c d e . (d -> c) -> (e -> d) -> e -> c b λ(c d e : *) (u : d -> c) (v : e -> d) (w : e) . u (v w)) ∀f . f -> f a λ(f : *) (z : f) . z
: ∀a b c d e . (d -> c) -> (e -> d) -> e -> c
```
It inserts some unnecessary type abstractions/applications, so I'm thinking of adding a …
> Implement a simple type inference algorithm

- implementation/src/Inference.hs
- implementation/src/Parser.y
Simplify some logic in the type checker/inferencer for System F. Also I changed the lambda notation from `\x . x` to `\x -> x` to be consistent with Haskell (I kept writing the wrong one).
@esdrw
> Simplify the type checker

- .hindent.yaml
- Makefile
- implementation/src/Inference.hs
Simplify the logic further and eliminate unnecessary type abstractions and applications.
Before:
```haskell
> (\x y -> x : forall a b . a -> b -> a) (\u v w -> u (v w) : forall c d e . (d -> c) -> (e -> d) -> e -> c) (\z -> z : forall f . f -> f)
λ(a b : *) . (λ(b a : *) . (λ(a b : *) (x : a) (y : b) . x) ∀c d e . (d -> c) -> (e -> d) -> e -> c b λ(c d e : *) (u : d -> c) (v : e -> d) (w : e) . u (v w)) ∀f . f -> f a λ(f : *) (z : f) . z
: ∀a b c d e . (d -> c) -> (e -> d) -> e -> c
```
Now:
```haskell
> (\x y -> x : forall a b . a -> b -> a) (\u v w -> u (v w) : forall c d e . (d -> c) -> (e -> d) -> e -> c) (\z -> z : forall f . f -> f)
(λ(x : ∀c d e . (d -> c) -> (e -> d) -> e -> c) (y : ∀f . f -> f) . x) λ(c d e : *) (u : d -> c) (v : e -> d) (w : e) . u (v w) λ(f : *) (z : f) . z
: …
```
> Simplify the logic further and eliminate unnecessary type abstractions and applications

- implementation/src/Inference.hs
Use the state monad to generate fresh unification variables. Don't just use the hint. In fact, don't even take a hint at all.
> Use the state monad to generate fresh unification variables

- implementation/examples/test.g
- implementation/src/Inference.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Distinguish between user-provided variables and system generated ones to prevent collisions.
> Distinguish between user-provided variables and system generated ones

- implementation/src/Inference.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Allow argument types to be annotated. This now works:
```haskell
> \(x : forall a . a -> a) -> x
λ(x : ∀a . a -> a) . x
: (∀a . a -> a) -> ∀a . a -> a
```
@esdrw
> Allow argument types to be annotated

- implementation/app/Main.hs
- implementation/implementation.cabal
- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/test/EvaluationSpec.hs
Implement (call-by-value) evaluation!
```haskell
> (\x -> x) (\y -> y)
(λ(x : ∀a . a -> a) . x) λ(a : *) (y : a) . y
: ∀a . a -> a
=> λ(a : *) (y : a) . y
> (\x y -> x) (\z -> z) (\w -> w)
(λ(x : ∀a . a -> a) (a : *) (y : ∀a . a -> a) . x) λ(a : *) (z : a) . z ∀a . a -> a λ(a : *) (w : a) . w
: ∀a . a -> a
=> λ(a : *) (z : ∀a . a -> a) . z
```
I'm puzzled about why `z` is the identity function in that second example though. Maybe that whole term has no principle type, so an arbitrary choice was made during type inference?
@esdrw
> Implement evaluation

- implementation/examples/test.g
- implementation/implementation.cabal
- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
For convenience, add let syntax which elaborates into a redex.
```haskell
> let f = (\x -> x) in f (\y -> y)
(λ(f : ∀a . a -> a) . f ∀a . a -> a λ(a : *) (y : a) . y) λ(a : *) (x : a) . x
: ∀a . a -> a
=> λ(a : *) (y : a) . y
```
I also fixed a bug in the evaluator.
@esdrw
> Add let syntax which elaborates into a redex

- implementation/implementation.cabal
- implementation/src/Context.hs
- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
- implementation/test/ContextSpec.hs
Add integers and addition—a monoid!
```haskell
let f = \x -> x + x : Int -> Int in
let g = \x -> f (f x) : Int -> Int in
f 3 + g 4
```
I also simplified the `Show` instances for terms because I was getting tired of maintaining them. Now they always use parentheses to eliminate ambiguity, even when they aren't strictly needed.
@esdrw
> Add integers

- implementation/examples/test.g
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Sort the imports. Apparently hindent sorts packages, but not individual items imported from a single package.
> Sort the imports

- implementation/examples/test.g
- implementation/src/Inference.hs
Previously, the `unify` function would try to instantiate variables to turn one type into another. Now, it can instantiate variables in both types to equate them. This allows more programs to type check without annotations. For example, this was previously rejected but works now:
```haskell
let apply = \f -> f : forall a b . (a -> b) -> a -> b in
let double = \x -> x + x : Int -> Int in
let twice = \(f : Int -> Int) (x : Int) -> f (f x) in
apply twice double 4
```
The inferred System F term is:
```haskell
((λ(apply : ∀a b . (a -> b) -> a -> b) . ((λ(double : Int -> Int) . ((λ(twice : (Int -> Int) -> Int -> Int) . (((((apply Int -> Int) Int -> Int) twice) double) 4)) (λ(f : Int -> Int) (x : Int) . (f (f x))))) (λ(x : Int) . (x + x)))) (λ(a b : *) (f : a -> b) . f))
```
And it's type is: …
> Make unification work in both directions

- implementation/examples/test.g
Add a fun example: Church-encoded lists.
```haskell
let nil = \i f -> i
: forall a b
. b
-> (a -> b -> b)
-> b in
let cons = \x l i f -> l (f x i) f
: forall a
. a
-> (forall b . b -> (a -> b -> b) -> b)
-> forall b . b -> (a -> b -> b) -> b in
let sum = \l -> l 0 (\x y -> x + y)
: (forall a . a -> (Int -> a -> a) -> a)
-> Int in
let myList = cons 3 (cons 4 (cons 5 nil)) in
sum myList
```
The result:
```haskell
((λ(nil : ∀a b . b -> (a -> b -> b) -> b) . ((λ(cons : ∀a . a -> (∀b . b -> (a -> b -> b) -> b) -> ∀b . b -> (a -> b -> b) -> b) . ((λ(sum : (∀a . a -> (Int -> a -> a) -> a) -> Int) . ((λ(myList : ∀b . b -> (Int -> b -> b) -> b) . (sum (λ(a : *) . (myList a)))) (((cons Int) 3) (λ(b : *) . ((((cons Int) 4) (λ(@4 : *) . ((((cons Int) 5) (λ(@6 : *) . ((nil Int) @6))) @4))) b))))) (λ(l …
```
> Add a fun example: Church-encoded lists

- implementation/src/Inference.hs
Move the `check e1 (PTUnifier u)` case to the (near) bottom in case any more useful cases might apply.
> Reorder some cases to potentially allow more programs to type check

- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Add basic calculator functionality with the proper order of operations. 😄 
```haskell
> 3 + 4
(3 + 4)
: Int
=> 7
> 5 + 3 * 2
(5 + (3 * 2))
: Int
=> 11
> 7 / 0
Runtime error: cannot divide 7 by 0
```
I also deleted the `Eq` instances for terms because the notion of equality on terms is ambiguous (definitional equality? equality of normal forms?).
@esdrw
> Add basic calculator functionality

- implementation/README.md
- implementation/app/Main.hs
- implementation/implementation.cabal
- implementation/stack.yaml
- scripts/Dockerfile
Add support for readline! This makes the REPL much nicer to use. You can navigate and search command history and...drumroll...use backspace! 😄 
I don't think Stack has a way to conditionally compile with readline depending on some flag. So, for now, readline is now a hard dependency. Unfortunately, users may need to set the `CFLAGS` and `LDFLAGS` flags to make this work (e.g., in their `.bashrc` or whatever), or else Stack will fail to build the `readline` package. It's ridiculous how primitive the process is for installing and using system libraries in 2018.
cc @esdrw
> Add support for readline

- implementation/src/Inference.hs
Fix a bug in the 'generalize' function that would sometimes lead to non-idempotent substitutions.
@esdrw
> Fix a bug in the 'generalize' function

- implementation/examples/test.g
- implementation/src/Lexer.x
- implementation/src/Parser.y
Switch from the `in` keyword to semicolons.
I think it's a little bit nicer since there isn't a `let` keyword.
@esdrw
> Switch from the 'in' keyword to semicolons

- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Add Booleans and conditionals (`if`/`then`/`else`). It's easier to play around with when there are a few basic types at your disposal. It's also interesting to see how this interacts with type inference:
So the "type" of `if` (if it were a function) is `∀α . Bool → α → α → α`.
@esdrw
> Add Booleans and conditionals

- implementation/src/Evaluation.hs
Remove redundancy in error messages (The string `Error: ` is already prefixed to error messages, so each error message doesn't need to say that).
Because we have static type checking, only one of these errors is actually possible at runtime: division by zero.
@esdrw
> Remove redundancy in error messages

- Makefile
Fail the build if there are ambiguities in the grammar.
@esdrw
> Fail the build if there are ambiguities in the grammar

- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Add support for lists and other N-ary constructors (but the only one currently is lists).
Right now you can't do anything with lists; you can only construct them. 😛
@esdrw
> Add support for lists and other N-ary constructors

- implementation/src/Inference.hs
- implementation/src/Substitution.hs
- implementation/src/Syntax.hs
Deliberately omit some type class instances to prevent mistakes.
@esdrw
> Deliberately omit some type class instances to prevent mistakes

- paper/calculus.tex
- paper/macros.tex
This PR deletes effect rows entirely, replacing them with "effects" which are just type variables and have no internal structure. There is no more "union" operator on effect rows, and we no longer need to deal with reordering, duplication, extension, row polymorphism, or any of that complexity. No more partial orders / equivalence relations either.
The system is now unprecedentedly simple, and I don't think it's possible for it to be any simpler!
In the examples below, note the following:
- ```haskell
Monoid a => t
```
is syntactic sugar for
```haskell
forall (a : *) (i : <Monoid a>) . t
```
Generalizing that,
```haskell
(Num a, Monoid a) => t
```
is syntactic sugar for
```haskell
forall (a : *) (i : <Num a>) (j : <Monoid a>) . t
```
- All the type abstractions and applications have been …
> Delete effect rows

- implementation/src/Parser.y
Fix how the parser handles type constructors.
```haskell
⨠ 3 : List Int
Error: Unable to unify Int with List Int
⨠ 3 : Foo A B C
Error: Unable to unify Int with Foo A B C
⨠ 3 : Foo a b c
Error: Unable to unify Int with Foo $0 $1 $2
⨠ 3 : Foo a (b -> c) d
Error: Unable to unify Int with Foo $0 ($1 → $2) $3
⨠ 3 : Foo a b c -> Bar d e f
Error: Unable to unify Int with Foo $0 $1 $2 → Bar $3 $4 $5
```
@esdrw
> Fix how the parser handles type constructors

- implementation/src/Inference.hs
- implementation/src/Parser.y
- implementation/src/Substitution.hs
- implementation/src/Syntax.hs
Delete arrow types and represent them as type constructors. Everything is the same to the user. I just removed some redundant logic by treating arrow types as just a special case of type constructors.
This PR only affects the Haskell implementation, not the paper.
@esdrw
> Delete arrow types and represent them as type constructors

- paper/main.tex
Remove operational semantics as a CCS concept since we don't have an operational semantics. 😛 
@esdrw
> Remove operational semantics as a CCS concept

- implementation/src/Inference.hs
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Replace missing type annotations with existential variables (instead of `Nothing`). This allows us to turn a `Maybe Type` into `Type`, which simplifies some things. Everything is the same from the user's point of view.
@esdrw
> Replace missing type annotations with existential variables

- paper/calculus.tex
- paper/intro.tex
Use the LaTeX (rather than the Tex) syntax for inline math. This appears to be the preferred syntax according to https://ro-che.info/articles/2018-04-12-correct-latex-formula-syntax. Note that we're already using the LaTeX syntax for block math (`\[` and `\]`).
This syntax is uglier, but one nice thing is that it's a little bit safer since opening has a different syntax than closing.
@esdrw
> Use the LaTeX (rather than the Tex) syntax for inline math

- Makefile
- implementation/src/Inference.hs
Flip the order of state and exception in the TypeCheck monad transformer stack.
Reader, Writer, and State all commute with each other. But Exception and State do not. It makes more sense to have `ExceptT` on the inside (i.e., the whole type is wrapped in an `Either`) because when an exception happens we don't care about the state.
I switched to using the monad transformer version of the state monad (i.e., `StateT` instead of `State`) because it makes these kinds of refactors (changing the order of monad transformers) easier.
Unfortunately `hindent` does not want to split the long definition of the `TypeCheck` monad onto multiple lines. :( So I have disabled the line-length check (and the other checks that come with it) for Haskell files. I think this is okay because it doesn't make sense …
> Flip the order of state and exception in the TypeCheck monad transformer stack

- implementation/src/Lexer.x
- implementation/src/Parser.y
- implementation/src/Syntax.hs
Replace the `*` kind with a `type` keyword. This is purely a cosmetic change. I'm making this change so I can demo this to my team without needing to explain how `*` has two meanings.
> Replace the '*' kind with a 'type' keyword

- paper/calculus.tex
Add missing subscripts in the typing and kinding rules. I'm not sure how these went missing for so long!
> Add missing subscripts in the typing and kinding rules

- implementation/app/Main.hs
- implementation/src/Evaluation.hs
- implementation/src/Inference.hs
- implementation/src/Lexer.x
Replace all uses of `return` with `pure` (why depend on `Monad` when `Applicative` will do the trick).
> Replace all uses of 'return' with 'pure'

- Makefile
- implementation/README.md
- implementation/package.yaml
- implementation/src/Inference.hs
- implementation/src/Lexer.x
- implementation/src/Substitution.hs
- implementation/src/Syntax.hs
This PR implements three improvements:
- Instead of passing the `--pedantic` flag to `stack build`, we put the corresponding `ghc-options` in `package.yml`. Now anyone can run `stack build` with no extra flags and get consistent results.
- We also move all language extensions to `package.yml`. Going forward, this will allow us to add extensions like `OverloadedStrings` that we want to apply globally. We maintain that it is better to have a consistent set of language extensions everywhere rather than have each file declare which extensions it relies on. That way it feels like each file is written in the same language.
- We add a comment to explain the mysterious `{-# OPTIONS_GHC -Wwarn=unused-imports #-}` line in `Lexer.x`.
> Put GHC options and extensions in `package.yml`

- implementation/examples/bools.g
- implementation/examples/church.g
- implementation/src/Syntax.hs
Fix a typo in the Church Booleans example. I could have given this a more specific type (`forall a b . a -> b -> b`) such that correctness follows from parametricity as a free theorem, but then `yes` and `no` would have differing types (which feels weird).
I also made a few stylistic changes.
> Fix a typo in the Church Booleans example

- Makefile
Rename the Docker repository from `effect-classes` to `paper`. This matches the S3 path where artifacts are uploaded to, and not having the name of the paper in the image tag will allow me to rename the paper more easily.
> Rename the Docker repository

- implementation/package.yaml
- implementation/src/Inference.hs
- implementation/src/Lexer.x
Turn on more GHC warnings.
These were recommended by
https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/.
> Turn on more GHC warnings
